### ISSUE TITLE
Search doesn't work anymore

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona-edu.github.io#156]
![image](https://user-images.githubusercontent.com/56451049/123790418-98090780-d8de-11eb-8e4d-25c0fc173e5d.png)

**Comment by bmesuere** [comment]
I emailed the algolia helpdesk because the issue seems to be at their side.

**Comment by bmesuere** [comment]
This was caused by our domain name switch. Will be fixed after the next indexing round.
