### ISSUE TITLE
Document data-large attribute for images

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona-edu.github.io#166]
Dodona supports a `data-large` attribute for `img` tags, to set an alternative image URL that is shown in the lightbox, instead of the `scr` attribute. This allows to set a thumbnail via the `src` attribute and a large version via the `data-large` attribute. This feature is not documented yet.

**Comment by BTWS2** [comment]
I found some documentation here https://docs.dodona.be/nl/references/exercise-description/#lightboxes
