### ISSUE TITLE
Different flavors of callouts

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona-edu.github.io#167]
The documentation of callouts may mention different types (using different colors) of callouts. Now, only the `callout-success` is used in the example. I use the `callout-info` by default, because it used the same blue color as the Dodona banner (`callout-success` uses a light grey color). May use a reference to the Bootstrap documentation.

**Comment by bmesuere** [comment]
This is because the shown "callout" is not an actual callout but something similar from the vuepress docs.
