### ISSUE TITLE
Explain Q&A module

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona-edu.github.io#169]
- for students: how to ask a question (if activated by teacher)
- for teachers: how to enable/disable the Q&A module; how to answer questions

**Comment by pdawyndt** [comment]
## Vragen stellen via de Q&A module van Dodona

In Dodona kan je doorlopend vragen stellen bij de code van ingediende oplossingen. Algemene vragen of vragen over een oefening stel je via de knop boven de code.

![image](https://user-images.githubusercontent.com/5736113/136263067-a93b0351-3af4-4c27-8b89-a9cafd98454a.png)

Vragen die specifiek over een bepaald deel van de code gaan, stel je door te klikken op de oranje knop naast het regelnummer in de rechterkantlijn. Gebruik Markdown om de opmaak van je vraag te verzorgen.

![image](https://user-images.githubusercontent.com/5736113/136263077-a6605b41-f281-4e51-afe1-1cada1f060af.png)

Als er één van je vragen beantwoord werd, dan ontvang je daarvan een notificatie. In de navigatiebalk word je via een rode stip bij het bel-icoon op de hoogte gebracht dat er notificaties zijn die je nog niet bekeken hebt.

![image](https://user-images.githubusercontent.com/5736113/136263090-72b0d532-970c-489b-a97e-e6fe2e77cf95.png)

Als je na het stellen van een vraag ondertussen zelf al het antwoord gevonden hebt op je vraag (rubber duck debugging), gelieve dan ook zelf in Dodona je vraag als beantwoord te markeren. Op die manier spaar je wat tijd uit van de elfen die alle vragen moeten beantwoorden.

![image](https://user-images.githubusercontent.com/5736113/136263103-607cdabc-ce85-4935-8928-a1a76c479bd2.png)

**Comment by BTWS2** [comment]
@bmesuere I guess this can be closed because of https://docs.dodona.be/nl/faq/annotations/?
